### ISSUE TITLE
Failed to send traces, BrokenPipeError (0.27.1)

### ISSUE THREAD

**Issue by mattbennett** [DataDog/dd-trace-py#1041]
We're seeing a lot of message like this from various pods in our kubernetes cluster:

```
Failed to send traces to Datadog Agent at <ddtrace.api.API object at 0x7f5f57eeccc0>: BrokenPipeError(32, 'Broken pipe')
```

It happens 1-10 times an hour across our four agents.

The agent runs on the node as a daemonset, configured as follows:

```
      - env:
        - name: DD_APM_ENABLED
          value: "true"
        - name: KUBERNETES
          value: "yes"
        - name: DD_COLLECT_KUBERNETES_EVENTS
          value: "true"
        - name: DD_LEADER_ELECTION
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_APM_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
...
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 512Mi
```

We have been experiencing these issues for a while and recently upgraded `ddtrace` to 0.27.1 in the hope that https://github.com/DataDog/dd-trace-py/pull/941 would fix it, but it has not.

The agent is running the latest version via this image tag `datadog/agent:latest`.

There are no `ERROR` level messages in the agent logs that correspond with the client errors. Nor do the errors correspond with any restarts of the daemonset pods. There have been a few agent restarts (the agent just seems to terminate without error) but they don't happen anything like as frequently as we see these `BrokenPipe` errors.

What should we do to get more information to debug this with?

Thanks
