### ISSUE TITLE
Cannot connect from asgi app (FastApi) to Datadog Agent running on Docker

### ISSUE THREAD

**Issue by jmandt** [DataDog/dd-trace-py#1626]
I am trying to connect to datadog from my fastapi backend. I am currently trying to do this on localhost using a docker-compose file to let both my datadog-agent and my backend-container run in the same network. 
Here is a minimal example 

### Which version of dd-trace-py are you using?
ddtrace==0.41.0

### Which version of the libraries are you using?
see in dockerfile below

### How can we reproduce your problem?

folder structure
```
dd-minimal
 - docker-compose.yml
 - backend-client
   - Dockerfile
   - app
     - main.py
```

docker-compose.yml
```

version: "3.7"

networks:
  my_network:

services:
  datadog:
    image: datadog/agent:latest
    environment:
     DD_API_KEY: <my-api-key>
     DD_APM_ENABLED: 'true'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports: 
      - "8126:8126/tcp"
    networks:
      - my_network
    
  backend-web-client:
    image: gql-backend-api
    build:
      dockerfile: Dockerfile
      context: ./backend-client
    environment:
      DD_TRACE_ANALYTICS_ENABLED: 'true'
      DD_AGENT_HOST: 172.21.0.2
    ports: 
      - "5555:8080"
    networks:
      - my_network
    depends_on: 
      - datadog
```

Dockerfile
```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

COPY ./app /app
RUN pip install ddtrace==0.41.0

CMD exec ddtrace-run gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0  main:api -k uvicorn.workers.UvicornWorker
```

main.py
```
import os

import uvicorn
from fastapi import FastAPI

api = FastAPI()

if __name__ == "__main__":
    uvicorn.run(api, host="127.0.0.1", port=int(os.environ.get("PORT", 8080)))
```

I run docker-compose up and then check the ip of my dd-container with 
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' dd-minimal_datadog_1
```

and update it in the compose file.

Any help would be very appreciated

### What is the result that you get?

```
- DATADOG TRACER DIAGNOSTIC - Agent not reachable. Exception raised: [Errno 111] Connection refused.
```

### What is the result that you expected?

connected successful and get my traces somewhere in datadog?

**Comment by majorgreys** [comment]
@jmandt Can you try configuring the agent container to accept traces from other containers?

https://docs.datadoghq.com/agent/docker/apm/?tab=linux#tracing-from-other-containers

```
environment:
     DD_API_KEY: <my-api-key>
     DD_APM_ENABLED: true
     DD_APM_NON_LOCAL_TRAFFIC: true
```
