### ISSUE TITLE
Unable to import module 'datadog_lambda.handler': No module named 'datadog_lambda'

### ISSUE THREAD

**Issue by amldvsk** [DataDog/dd-trace-py#3302]
Installing everything according to this documentation 
https://docs.datadoghq.com/serverless/installation/python/?tab=serverlessframework

using serverless 
Framework Core: 2.72.1 (local)
Plugin: 5.5.4
SDK: 4.3.0
Components: 3.18.2

layer was added to the lambda but we get this error

LOGS	Name: datadog-agent	State: Subscribed	Types: [platform,function,extension]
EXTENSION	Name: datadog-agent	State: Ready	Events: [INVOKE,SHUTDOWN]
[ERROR] Runtime.ImportModuleError: Unable to import module 'datadog_lambda.handler': No module named 'datadog_lambda'
Traceback (most recent call last):

**Comment by astuyve** [comment]
Hi @amldvsk - which version of the datadog extension layer and datadog python layer are you using?

Can you share a redacted copy of your `serverless.yml` file as well as a screenshot of the Layer section of your Lambda function in the AWS console?

**Comment by amldvsk** [comment]
![Screen Shot 2022-02-23 at 9 36 18](https://user-images.githubusercontent.com/7415022/155277867-d77424b0-b5e5-4584-8ebc-9eb8270375e2.png)


```
provider:
  name: aws
  runtime: python3.8
  environment:
    DD_ENV: dev3
    DD_SERVICE: exercise
    DD_VERSION: 1
    DD_TAGS: group:abs
```

```
custom:
  datadog:
    addExtension: true
    apiKey: aa**********************d5
```
