### ISSUE TITLE
Log is filled with warning `Unable to parse kinesis streams data string` when sending `gzip`ed data to `Kinesis`

### ISSUE THREAD

**Issue by IlyaMichlin** [DataDog/dd-trace-py#4735]
### Summary of problem
When sending `gzip`ed data to `Kinesis` and `ddtrace` logs the waning `Unable to parse kinesis streams data string` for every request.

While it is stated in [get_kinesis_data_object](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/contrib/botocore/patch.py#L168) that it support types such as `gzip`, it does not do so and instead logs the warning.

### Which version of dd-trace-py are you using?
`ddtrace==1.6.3`

### Which version of pip are you using?
`pip==22.3.1`

### Which libraries and their versions are you using?

```
attrs==22.1.0
boto3==1.26.22
botocore==1.29.22
bytecode==0.14.0
cattrs==22.2.0
ddsketch==2.0.4
ddtrace==1.6.3
envier==0.4.0
jmespath==1.0.1
jsonschema==4.17.3
packaging==21.3
protobuf==4.21.10
pyparsing==3.0.9
pyrsistent==0.19.2
python-dateutil==2.8.2
s3transfer==0.6.0
six==1.16.0
tenacity==8.1.0
typing_extensions==4.4.0
urllib3==1.26.13
xmltodict==0.13.0
```

### How can we reproduce your problem?
```
version: '3.9'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=kinesis
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4568
      - KINESIS_INITIALIZE_STREAMS=stream1
    ports:
      - "4568:4568"
```

```
import gzip
import io

import boto3
from ddtrace import patch

patch(botocore=True)


def compress_data(data: str) -> bytes:
    out = io.BytesIO()

    with gzip.GzipFile(fileobj=out, mode="w") as fo:
        fo.write(data.encode())

    bytes_obj = out.getvalue()
    return bytes_obj


record = {
    "Data": compress_data("some_data\n"),
    "PartitionKey": str(123),
}

kinesis = boto3.client("kinesis", region_name="us-east-1", endpoint_url="http://localhost:4568")
kinesis.put_records(StreamName="stream1", Records=[record])

```

### What is the result that you get?
Warning `ddtrace.contrib.botocore.patch.TraceInjectionDecodingError: Unable to parse kinesis streams data string`

### What is the result that you expected?
Trace the record.
