### ISSUE TITLE
Dropping traces to Datadog Agent after server restart

### ISSUE THREAD

**Issue by ArcLightSlavik** [DataDog/dd-trace-py#5533]
### Summary of problem
When our python server restarts the datadog client drops a few traces, visible in the logs below.
While the issue itself doesn't bother us, we constantly get alerts in sentry about these traces dropping. In my mind it's pretty identical to this error https://github.com/DataDog/dd-trace-py/issues/3954, which we also had but after https://github.com/DataDog/dd-trace-py/pull/4692 it seems to have vanished

<img width="1029" alt="Screenshot 2023-04-12 at 20 46 37" src="https://user-images.githubusercontent.com/31127044/231542229-0080950f-8d35-429f-b6f2-ee4d47a4e477.png">
<img width="1021" alt="Screenshot 2023-04-12 at 20 46 44" src="https://user-images.githubusercontent.com/31127044/231542255-99280815-9069-49eb-a672-59ce5cc2602e.png">

### Which version of dd-trace-py are you using?
1.8.0

### Which version of pip are you using?
-

### Which libraries and their versions are you using?
-

### How can we reproduce your problem?
-

### What is the result that you get?
Error logged into sentry

### What is the result that you expected?
Ability to ignore error / not logging it at all

**Comment by ArcLightSlavik** [comment]
Hello @Yun-Kim !

I am not quite sure why application restarting results in failure to send. I do see have this though, maybe it could help somehow? If not I'll ask around more.
```
    app:
      name: "dpd-uk-v2"
      command:
        - "/usr/bin/dumb-init"
        - "--"
        - ddtrace-run
      args:
        - gunicorn
        - "--bind"
        - "0.0.0.0:8000"
        - "--access-logfile"
        - "-"
        - "-k"
        - uvicorn.workers.UvicornWorker
        - "-w"
        - "2"
        - "-t"
        - "60"
        - "--graceful-timeout"
        - "60"
        - "fake_app"
```

>is it possible to filter these logs on Sentry instead

That's exactly what I would love to achieve, but that's the part I am confused about. I assume I would need to ignore the specific ConnectionRefusedError exception from ddtrace?
