### ISSUE TITLE
Django Integration Not Picking up version from DD_VERSION Env Var

### ISSUE THREAD

**Issue by etimberg** [DataDog/dd-trace-py#6247]
### Summary of problem

I have a django app with ddtrace configured and enabled. The app is set up with:

* Django running via gunicorn
* Celery for background tasks + redis
* Postgres as the database

The entire thing is deployed into kubernetes on GCP. In the yaml files for the API container and the worker container I have the setup shown below. I have verified that `DD_VERSION` is correctly set into the container and is the correct value at runtime. However, the value does not seem to get attached to the spans sent to datadog. The curious thing is that the other `DD_*` environment variables do work as the spans are correctly tagged for the environment and the custom headers do apply.

The exact same config is used for the celery worker and in that container the version is correctly attached to the traces. This leads me to believe that this is something specific to django integration.

<details>
<summary>k8s config</summary>

```yaml
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: foo-api-certificate
spec:
  domains:
  - foo.example.com
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
    tags.datadoghq.com/version: <VERSION>
  name: foo-api-service
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: foo-api
  sessionAffinity: None
  type: NodePort
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "foo"
  namespace: "default"
  labels:
    app: "foo"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "foo"
  template:
    metadata:
      labels:
        app: "foo"
        tags.datadoghq.com/version: <version>
    spec:
      containers:
      - name: <name>
        image: <image>
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "ddtrace-run gunicorn --bind :8000 --max-requests 100 --max-requests-jitter 25 --workers 4 app_module"]
        resources:
          requests:
            memory: "2048Mi"
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog
              key: api-key
        - name: DD_ENV
          value: "foo"
        - name: DD_AGENT_HOST
          value: datadog.default.svc.cluster.local
        - name: DD_TRACE_HEADER_TAGS
          value: origin:http.origin,referer:http.referer,requestor-role:app.requestor-role
        - name: DD_VERSION
          value: <VERSION>
```

</details>

### Which version of dd-trace-py are you using?

1.15.1

### Which version of pip are you using?

Not using pip, using poetry 1.1.22

### Which libraries and their versions are you using?

* Django 4.2
* django-redis 5.2.0
* Celery 5.2.7
* gunicorn 20.0.4

### What is the result that you get?

Django traces are missing a version span tag.

### What is the result that you expected?

Django traces have a version span tag.
