### ISSUE TITLE
How to log within a span of a trace?

### ISSUE THREAD

**Issue by wenbochang** [DataDog/dd-trace-py#686]
Sorry if I'm doing something silly, but I can't seem to get the log to show up in a span:

```
with tracing.start_span('db-span', context=context) as span:
    span.set_tag('tag_key', 'tag_value')
    span.set_tag('event', 'server event')
    span.log_kv({'message': 'hello from client'})
 ```

I can see the tags (also isn't event suppose to log according to [opentracing spec](https://github.com/opentracing/specification/blob/1be630515dafd4d2a468d083300900f89f28e24d/semantic_conventions.md#log-fields-table)? ):

<img width="335" alt="screen shot 2018-11-01 at 1 24 26 pm" src="https://user-images.githubusercontent.com/4371899/47877586-7f688c80-ddd9-11e8-9679-6667536e614b.png">

But no logs

<img width="664" alt="screen shot 2018-11-01 at 1 25 04 pm" src="https://user-images.githubusercontent.com/4371899/47877626-914a2f80-ddd9-11e8-8cd3-ddd5239c176d.png">

Maybe my docker-compose is missing additional settings? I did include `dd_logs_enabled`:

```
    image: datadog/agent:6.5.2
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_APM_ENABLED: "true"
      DD_LOGS_ENABLED: "true"
      DD_TAGS: "env:platform"
      NON_LOCAL_TRAFFIC: "true"
```
